version: "3.9"
services:
  devcontainer:
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - v9fs-linux:/home/vscode/linux
      - v9fs-ccache:/ccache
      - v9fs-build:/build
    networks:
      - default
    ports:
      - 3000
volumes:
  v9fs-linux:
    external: true
  v9fs-ccache:
    external: true
  v9fs-build:
    external: true
