version: "3.9"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~:/home/user
      - ~/Documents/Journals:/workspaces/Journals
      - ~/images:/boot
      - v9fs-linux:/workspaces/linux
      - v9fs-ccache:/ccache
      - v9fs-build:/build
    networks:
      - default
    ports:
      - 3000
volumes:
  v9fs-linux:
    external: true
  v9fs-ccache:
    external: true
  v9fs-build:
    external: true
